// src/pages/layout.js

import { Inter } from "next/font/google";
import "./globals.css";

// Initialize Inter font
const inter = Inter({ subsets: ["latin"] });

// Export metadata for server component
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component, assumed to be a server component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
